SELECT  
 PSSOA.CD_PSSOA, 
 PSSOA.CD_PSSOA_EXTRN, 
 case when 1=2 then ISNULL(PSSOA.NOME_SOCIAL, PSSOA.NM_PSSOA) ELSE PSSOA.NM_PSSOA END NM_PSSOA, 
 PSSOA.ID_PSSOA_SEXO, 
 PSSOA.DT_PSSOA_NASCI, 
 PSSOA.DT_PSSOA_REG, 
 PSSOA.NO_PSSOA_TEL_RES, 
 PSSOA.NO_PSSOA_TEL_COM, 
 PSSOA.NO_PSSOA_TEL_CEL, 
 PSSOA.NM_PSSOA_EMAIL, 
 PSSOA.ID_PSSOA_TITLR, 
 PSSOA.ST_PSSOA, 
 DS_ENDRC, 
 NO_ENDRC, 
 DS_COMPL, 
 NO_CEP, 
 DS_BAIRRO, 
 DS_CIDDE, 
 CD_IBGE, 
 ENDRC.CD_ESTDO, 
 ENDRC.CD_PAIS, 
 EMPSA.CD_EMPSA, 
  NM_EMPSA,
  (SELECT
     TPDOC.CD_TPDOC AS [codigo],
     TPDOC.NM_TPDOC AS [documento],
     PSDOC.DS_PSDOC AS [numero]
   FROM PSDOC 
     INNER JOIN TPDOC ON (TPDOC.CD_TPDOC = PSDOC.CD_TPDOC)
   WHERE PSDOC.CD_PSSOA = PSSOA.CD_PSSOA 
  FOR JSON PATH) AS LS_PSSOA_DOCMT,
  (SELECT
     CTRNH.NO_CTRNH AS [numero],
     CONVERT(VARCHAR,CTRNH.DT_CTRNH_VLIDD, 103) AS [dataValidade],
     CTRNH.NO_CTRNH_CONVN AS [convenio] 
   FROM CTRNH 
   WHERE CTRNH.CD_PSSOA = PSSOA.CD_PSSOA 
  FOR JSON PATH) AS LS_PSSOA_CTRNH, 
  PSSOA_GSTR.NM_PSSOA AS NM_PSSOA_GSTR, 
  PSSOA_GSTR.NM_PSSOA AS NM_PSSOA_ENF 
 FROM PSSOA 
  LEFT JOIN ENDRC ON (PSSOA.CD_ENDRC = ENDRC.CD_ENDRC)
  LEFT JOIN CIDDE ON (ENDRC.CD_CIDDE = CIDDE.CD_CIDDE AND ENDRC.CD_ESTDO = CIDDE.CD_ESTDO AND ENDRC.CD_PAIS = CIDDE.CD_PAIS)
  LEFT JOIN EMPSA ON (PSSOA.CD_EMPSA_CLENT = EMPSA.CD_EMPSA)
LEFT JOIN PPSUS ON PPSUS.CD_PSSOA = PSSOA.CD_PSSOA 
LEFT JOIN PSUND ON PSUND.CD_PSUND = PPSUS.CD_PSUND
LEFT JOIN PSSOA PSSOA_GSTR ON PSSOA_GSTR.CD_PSSOA = PSUND.CD_PSSOA_PROF
LEFT JOIN PSSOA PSSOA_ENF ON PSSOA_ENF.CD_PSSOA = PSUND.CD_PSSOA_ENF
 WHERE PSSOA.TP_PSSOA = 'C' AND (PSSOA.ST_PSSOA = 'A' OR PSSOA.ST_PSSOA = 'I') 
  AND EXISTS (  
 		 SELECT 1 
 		 FROM TPDOC 
 		 	 INNER JOIN PSDOC ON ( PSDOC.CD_TPDOC = TPDOC.CD_TPDOC ) 
 		 WHERE PSDOC.CD_PSSOA = PSSOA.CD_PSSOA 
 		      AND dbo.FN_REMOVER_CARACTERES(PSDOC.DS_PSDOC, '^0-9') like '%156173336%' 
 		      AND TPDOC.NM_TPDOC = 'CPF' 
  ) 
 ORDER BY PSSOA.NM_PSSOA, PSSOA.DT_PSSOA_NASCI  OFFSET 0 ROWS FETCH NEXT 25 ROWS ONLY

