USE [master]
GO

/****** Object:  Database xxxxxxx   ******/
CREATE DATABASE Maintenance ON  PRIMARY 
( NAME = N'Maintenance', FILENAME = N'G:\Data\Maintenance.mdf' , SIZE = 10240MB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
( NAME = N'Maintenance_log', FILENAME = N'F:\Log\Maintenance_log.ldf' , SIZE = 1024MB , MAXSIZE = 2048GB , FILEGROWTH = 0)
GO

ALTER DATABASE Maintenance SET COMPATIBILITY_LEVEL = 100
GO

ALTER DATABASE Maintenance SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE Maintenance SET ANSI_NULLS ON 
GO

ALTER DATABASE Maintenance SET ANSI_PADDING ON 
GO

ALTER DATABASE Maintenance SET ANSI_WARNINGS ON 
GO

ALTER DATABASE Maintenance SET ARITHABORT ON 
GO

ALTER DATABASE Maintenance SET AUTO_CLOSE OFF 
GO

ALTER DATABASE Maintenance SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE Maintenance SET AUTO_SHRINK OFF 
GO

ALTER DATABASE Maintenance SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE Maintenance SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE Maintenance SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE Maintenance SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE Maintenance SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE Maintenance SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE Maintenance SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE Maintenance SET  ENABLE_BROKER						-- DBA
GO

ALTER DATABASE Maintenance SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE Maintenance SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE Maintenance SET TRUSTWORTHY ON						-- DBA
GO

ALTER DATABASE Maintenance SET ALLOW_SNAPSHOT_ISOLATION ON			-- DBA
GO

ALTER DATABASE Maintenance SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE Maintenance SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE Maintenance SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE Maintenance SET RECOVERY FULL						-- DBA 
GO

ALTER DATABASE Maintenance SET  MULTI_USER 
GO

ALTER DATABASE Maintenance SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE Maintenance SET DB_CHAINING OFF 
GO

ALTER DATABASE Maintenance SET  READ_WRITE 
GO