CREATE OR ALTER TRIGGER TG_AUDIT_QUEST ON dbo.QUEST
FOR INSERT, UPDATE, DELETE
AS BEGIN
DECLARE @Operacao char(1)

IF EXISTS(SELECT 1 FROM INSERTED)
BEGIN
        SET @Operacao = 'I' 
END
IF EXISTS(SELECT 1 FROM DELETED)
BEGIN
        IF (@Operacao IS NULL)
                SET @Operacao = 'D' 
        ELSE
                SET @Operacao = 'U' 
END
IF @Operacao = 'I' 
BEGIN
 BEGIN TRY 
        INSERT INTO QUEST_audit(	
        CD_QUEST,
		NM_QUEST,
		TP_QUEST,
		ST_QUEST,
		DS_QUEST_MSCRA,
		NO_QUEST_ITINI,
		NO_QUEST_ITFIM,
		NM_QUEST_IMG,
		ID_QUEST_EXAME_FISIC_PEP,
		ID_QUEST_RESUL_EXAME_PEP,
		ID_QUEST_OBRG,
		CD_QUEST_EXTRN,
		PERM_QUEST_CLENT,
		PERM_QUEST_GSTOR,
		PERM_QUEST_PROSD,
		PERM_QUEST_ATESC,
		USR_REG,
		ID_QUEST_OBJETIVA_SOAP,
		ID_QUEST_FAVRT,
		CD_TERMO,
		NO_QUEST_ITINI_IDEAL,
		NO_QUEST_ITFIM_IDEAL,
		Operacao)
        SELECT         		
        CD_QUEST,
		NM_QUEST,
		TP_QUEST,
		ST_QUEST,
		DS_QUEST_MSCRA,
		NO_QUEST_ITINI,
		NO_QUEST_ITFIM,
		NM_QUEST_IMG,
		ID_QUEST_EXAME_FISIC_PEP,
		ID_QUEST_RESUL_EXAME_PEP,
		ID_QUEST_OBRG,
		CD_QUEST_EXTRN,
		PERM_QUEST_CLENT,
		PERM_QUEST_GSTOR,
		PERM_QUEST_PROSD,
		PERM_QUEST_ATESC,
		USR_REG,
		ID_QUEST_OBJETIVA_SOAP,
		ID_QUEST_FAVRT,
		CD_TERMO,
		NO_QUEST_ITINI_IDEAL,
		NO_QUEST_ITFIM_IDEAL,
		@Operacao 
        FROM INSERTED
 END TRY 
 BEGIN CATCH  
      DECLARE @ErrorMessageAdd NVARCHAR(4000), @ErrorSeverityAdd INT;      
      SELECT @ErrorMessageAdd = 'Trigger: TG_AUDIT_QUEST; Operação: ' + @Operacao + '; - Erro na linha ' + CAST(ERROR_LINE() AS VARCHAR(10)) + ' - ' + ERROR_MESSAGE(), @ErrorSeverityAdd = ERROR_SEVERITY();
      RAISERROR(@ErrorMessageAdd, @ErrorSeverityAdd, 1);    
 END CATCH 
END
ELSE IF @Operacao = 'U' 
BEGIN
 BEGIN TRY 
        INSERT INTO QUEST_audit(	
        CD_QUEST,
		NM_QUEST,
		TP_QUEST,
		ST_QUEST,
		DS_QUEST_MSCRA,
		NO_QUEST_ITINI,
		NO_QUEST_ITFIM,
		NM_QUEST_IMG,
		ID_QUEST_EXAME_FISIC_PEP,
		ID_QUEST_RESUL_EXAME_PEP,
		ID_QUEST_OBRG,
		CD_QUEST_EXTRN,
		PERM_QUEST_CLENT,
		PERM_QUEST_GSTOR,
		PERM_QUEST_PROSD,
		PERM_QUEST_ATESC,
		USR_REG,
		ID_QUEST_OBJETIVA_SOAP,
		ID_QUEST_FAVRT,
		CD_TERMO,
		NO_QUEST_ITINI_IDEAL,
		NO_QUEST_ITFIM_IDEAL,
		Operacao)
        SELECT         		
        CD_QUEST,
		NM_QUEST,
		TP_QUEST,
		ST_QUEST,
		DS_QUEST_MSCRA,
		NO_QUEST_ITINI,
		NO_QUEST_ITFIM,
		NM_QUEST_IMG,
		ID_QUEST_EXAME_FISIC_PEP,
		ID_QUEST_RESUL_EXAME_PEP,
		ID_QUEST_OBRG,
		CD_QUEST_EXTRN,
		PERM_QUEST_CLENT,
		PERM_QUEST_GSTOR,
		PERM_QUEST_PROSD,
		PERM_QUEST_ATESC,
		USR_REG,
		ID_QUEST_OBJETIVA_SOAP,
		ID_QUEST_FAVRT,
		CD_TERMO,
		NO_QUEST_ITINI_IDEAL,
		NO_QUEST_ITFIM_IDEAL,
		@Operacao 
        FROM INSERTED
 END TRY 
 BEGIN CATCH
      DECLARE @ErrorMessageUpd NVARCHAR(4000), @ErrorSeverityUpd INT;      
      SELECT @ErrorMessageUpd = 'Trigger: TG_AUDIT_QUEST; Operação: ' + @Operacao + '; - Erro na linha ' + CAST(ERROR_LINE() AS VARCHAR(10)) + ' - ' + ERROR_MESSAGE(), @ErrorSeverityUpd = ERROR_SEVERITY();
      RAISERROR(@ErrorMessageUpd, @ErrorSeverityUpd, 1);     
 END CATCH 
END
ELSE IF @Operacao = 'D' 
BEGIN
 BEGIN TRY 
        INSERT INTO QUEST_audit(	
        CD_QUEST,
		NM_QUEST,
		TP_QUEST,
		ST_QUEST,
		DS_QUEST_MSCRA,
		NO_QUEST_ITINI,
		NO_QUEST_ITFIM,
		NM_QUEST_IMG,
		ID_QUEST_EXAME_FISIC_PEP,
		ID_QUEST_RESUL_EXAME_PEP,
		ID_QUEST_OBRG,
		CD_QUEST_EXTRN,
		PERM_QUEST_CLENT,
		PERM_QUEST_GSTOR,
		PERM_QUEST_PROSD,
		PERM_QUEST_ATESC,
		USR_REG,
		ID_QUEST_OBJETIVA_SOAP,
		ID_QUEST_FAVRT,
		CD_TERMO,
		NO_QUEST_ITINI_IDEAL,
		NO_QUEST_ITFIM_IDEAL,
		Operacao)
        SELECT         		
        CD_QUEST,
		NM_QUEST,
		TP_QUEST,
		ST_QUEST,
		DS_QUEST_MSCRA,
		NO_QUEST_ITINI,
		NO_QUEST_ITFIM,
		NM_QUEST_IMG,
		ID_QUEST_EXAME_FISIC_PEP,
		ID_QUEST_RESUL_EXAME_PEP,
		ID_QUEST_OBRG,
		CD_QUEST_EXTRN,
		PERM_QUEST_CLENT,
		PERM_QUEST_GSTOR,
		PERM_QUEST_PROSD,
		PERM_QUEST_ATESC,
		USR_REG,
		ID_QUEST_OBJETIVA_SOAP,
		ID_QUEST_FAVRT,
		CD_TERMO,
		NO_QUEST_ITINI_IDEAL,
		NO_QUEST_ITFIM_IDEAL,
		@Operacao FROM DELETED
 END TRY 
 BEGIN CATCH
      DECLARE @ErrorMessageDel NVARCHAR(4000), @ErrorSeverityDel INT;      
      SELECT @ErrorMessageDel = 'Trigger: TG_AUDIT_QUEST; Operação: ' + @Operacao + '; - Erro na linha ' + CAST(ERROR_LINE() AS VARCHAR(10)) + ' - ' + ERROR_MESSAGE(), @ErrorSeverityDel = ERROR_SEVERITY();
      RAISERROR(@ErrorMessageDel, @ErrorSeverityDel, 1);     
 END CATCH 
END
END
GO