BACKUP DATABASE [P_YOUR_DATABASE] 
TO DISK = N'/var/opt/mssql/data/P_YOUR_DATABASE.bak' 
WITH NOFORMAT
, NOINIT
, NAME = N'P_YOUR_DATABASE-Full Database Backup'
, SKIP
, NOREWIND
, STATS = 5
, COMPRESSION

