BACKUP DATABASE [P_HEALTHMAP_CLINICADOC] 
TO DISK = N'/var/opt/mssql/data/P_HEALTHMAP_CLINICADOC.bak' 
WITH NOFORMAT
, NOINIT
, NAME = N'P_HEALTHMAP_CLINICADOC-Full Database Backup'
, SKIP
, NOREWIND
, STATS = 5
, COMPRESSION

