RESTORE DATABASE [H_HEALTHMAP_CAREPLUS_TDE] 
FROM  DISK = N'/home/remote/H_HEALTHMAP_CAREPLUS_TDE.bak' 
WITH  FILE = 1,  
MOVE N'P_HEALTHMAP' TO N'/var/opt/mssql/data/H_HEALTHMAP_CAREPLUS_TDE.mdf',  
MOVE N'P_HEALTHMAP_log' TO N'/var/opt/mssql/data/H_HEALTHMAP_CAREPLUS_TDE_log.ldf',  
NOUNLOAD,  STATS = 5
