USE YOUR_DATABASE
GO

BEGIN TRANSACTION

BEGIN TRY
delete from YOUR_DATABASE.dbo.TRANSACIONADORES
from YOUR_DATABASE.dbo.TRANSACIONADORES as t1
inner join 
		(  select Cod from
			(	SELECT 
				 Cod=TRACOD
				,Nome=TRANOM
				,Nat=TRANATJURIDICA
				,CPF=TRACPF
				,CNPJ=TraCnpj
				,Origem='Transacionadores'
				,Banco=TRABANCOD
				,Age=TRAAGECOD
				,Conta=TRACODCONTABANCO 
				  FROM YOUR_DATABASE.dbo.TRANSACIONADORES T 
				 WHERE T.TRASIT =1

				 UNION

				 SELECT TRACOD
				,TRANOM
				,TRANATJURIDICA
				,TRACPF
				,TraCnpj
				, 'TraContasLevel1'
				,TraConBanCod
				,TraconAgeCod
				,TraConNumCon

				  FROM YOUR_DATABASE.dbo.TRANSACIONADORES T 
				 INNER JOIN YOUR_DATABASE.dbo.TRACONTASLEVEL1  C ON T.TRACOD=C.TRACONCOD
				 WHERE T.TRASIT =1 

			) x
			WHERE X.BANCO IN (1)
		) as t2
		on t1.TraCod = t2.Cod

END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		SELECT ERROR_NUMBER(), ERROR_MESSAGE()
	END CATCH

--COMMIT TRANSACTION

--SELECT @@TRANCOUNT