use Maintenance
go

create or alter view Management.vw_MonitoringLogRecordsPaul
with encryption
as

SELECT
    [s_tst].[session_id],
	[s_er].open_transaction_count,
	[s_es].status,
    [s_es].[login_name] AS [Login Name],
    DB_NAME (s_tdt.database_id) AS [Database],
    [s_tdt].[database_transaction_begin_time] AS [Begin Time],			-- how many log records have been generated by the transaction
    [s_tdt].[database_transaction_log_bytes_used] AS [Log Bytes],		-- how much log space has been taken up by those log records
    [s_tdt].[database_transaction_log_bytes_reserved] AS [Log Rsvd],	-- how much log space has been reserved in case the transaction rolls back
    [s_est].text AS [Last T-SQL Text],									-- the last T-SQL that was executed in the context of the transaction
    [s_eqp].[query_plan] AS [Last Plan]									-- the last query plan that was executed (only for currently executing plans)
FROM
    sys.dm_tran_database_transactions [s_tdt]
JOIN
    sys.dm_tran_session_transactions [s_tst]
ON
    [s_tst].[transaction_id] = [s_tdt].[transaction_id]
JOIN
    sys.[dm_exec_sessions] [s_es]
ON
    [s_es].[session_id] = [s_tst].[session_id]
JOIN
    sys.dm_exec_connections [s_ec]
ON
    [s_ec].[session_id] = [s_tst].[session_id]
LEFT OUTER JOIN
    sys.dm_exec_requests [s_er]
ON
    [s_er].[session_id] = [s_tst].[session_id]
CROSS APPLY
    sys.dm_exec_sql_text ([s_ec].[most_recent_sql_handle]) AS [s_est]
OUTER APPLY
    sys.dm_exec_query_plan ([s_er].[plan_handle]) AS [s_eqp]

WHERE [s_es].session_id <> @@SPID
     
